name: Deploy Jekyll to GitHub Pages

on:
  push:
    branches:
      - main  # 默认分支为 main
  workflow_dispatch:  # 支持手动触发部署

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.1'  # 使用适合你 Jekyll 版本的 Ruby 版本

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install  # 安装 Gemfile 中声明的所有依赖

      - name: Clean cache
        run: |
          rm -rf ./_site  # 清理旧的构建文件
          rm -rf .jekyll-cache  # 清理 Jekyll 缓存

      - name: Build the site with Jekyll
        run: |
          bundle exec jekyll build  # 构建站点到 _site（或你指定的目录）

      - name: List the contents of docs directory
        run: ls -l docs
  
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs  # 构建结果目录

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          branch: gh-pages  # 部署到 gh-pages 分支
          folder: ./_site  # 输出目录
