name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main # 或者你的默认分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0 # 指定 Ruby 版本
          bundler-cache: true # 自动安装 Gemfile 中的依赖

      - name: Build Jekyll site
        run: bundle exec jekyll build --source docs --destination docs/_site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_site
